set (BOOST_MIN_VERSION 1.55)
set(Boost_USE_STATIC_LIBS ON)
set(Boost_USE_MULTITHREADED ON)
set(Boost_USE_STATIC_RUNTIME OFF)


if (${CMAKE_SYSTEM_NAME} MATCHES "Linux")
set (NESTLE_PLATFORM_TYPE "desktop")
set (NESTLE_PLATFORM_NAME "linux")
#set (NESTLE_PLATFORM "${NESTLE_PLATFORM_TYPE}_${NESTLE_PLATFORM_NAME}")
endif ()
